jasypt:
   encryptor:
      password: ${jasyptpwd}
      algorithm: PBEWithMD5AndDES

spring:
   datasource:
      driver-class-name: 
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: 
      username: 
      password: 
      hikari:
         poolName: pool

server:
   port: 8083
   servlet:
      context-path: /microservicio

